### ISSUE TITLE
Support for other databases

### ISSUE THREAD

**Issue by shemsargent-rvtd** [codefoundries/UniversalRelayBoilerplate#173]
So I am happy to find a Node.js stack that has React, Relay, Material UI, and many other useful modules and tools. This is by far the best fit to my business app dev needs that I have found after a lot of searching. The big challenge I foresee is integrating URB with our existing database in MySQL. I think I will need to interface GraphQL with Sequelize instead of Cassandra, at least to get a testable system up and running. I consider moving to Cassandra or another NoSQL DB as an option down the road.

So, adding support for MySQL and other databases would be good for me, and I am willing to contribute code to help that along. It might attract other devs who need RDBMS solutions to use and contribute as well.

I also am really interested in beta testing Rebar with you. I need the authentication and some other modules. Any chance I might get an invite? Thanks!

**Comment by thelordoftheboards** [comment]
@shemsargent-rvtd thank you for the kind words.

Using SQL with Sequelize should definitely be possible. However, I am not sure if it can be done without forking the project and breaking the Cassandra compatibility. I would suggest you start your research from [ObjectPersisterMemory.js](https://github.com/codefoundries/UniversalRelayBoilerplate/blob/master/graphql/ObjectPersisterMemory.js) and [ObjectPersisterCassandra.js](https://github.com/codefoundries/UniversalRelayBoilerplate/blob/master/graphql/ObjectPersisterCassandra.js). If you could integrate SQL on that level, without breaking the Cassandra functionality, that would be a total win and I'd love to have it supported within URB as first class citizen. One thing to consider is that the object manager classes would have to get extended to support search functionality, right now they only allow retrieving one item by ID, or list of items by foreign key.

As for using Rebar please add me on twitter [@Lordoftheboards](https://twitter.com/Lordoftheboards) and we can DM. I would be happy to help.

**Comment by thelordoftheboards** [comment]
Here is a plan of what could be done to support multiple databases with a relatively low level of effort. The goals and assumptions of the change are:

* Object Manager will be modified so that it can be set on a table/object type level. This would allow the use of different databases within the same application.
* Object Manager will also assume the role of managing models and creation of tables, essentially providing a layer over express-cassandra and other ORMs that would be used for other databases.
* Object Manager will completely abstract away all queries to databases, so it would have to include all methods for including search by string, etc.
* As a side effect, Object Managers can be provided as a front-end to 3rd party APIs, micro services, Santa's gnomes, lambda functions, Saruman's palantir, etc. This would allow to use micro services as a back end while keeping the main application relatively simple by supporting the graphql server, server-side rendering, security and authentication.
* Data Loader will be in the centerpiece of data access as it is currently, and it will pass on requests to object managers. As a side effect, no JOINs will be used when querying, even if a SQL database is used.
* It is assumed that all Object Manger implementations for any database will use the Object Type classes as output. Alternatively, such translation can be implemented on the data loader level. Either way, GraphQL has to be passed the proper object types.
* Upon insert, new PKs will be UUIDs generated within URB. Any kind of auto-increment functionality available in most RDBMs would thus not be supported. This will allow to keep the complexity of the entire contraption fairly low.
* The reliance on the cassandra-driver UUID class would be removed, and UUIDs will be represented by a string.

In Code Foundries we are willing to do the work on the Object Managers and Data Loader and provide the support for Cassandra. The in-memory implementation would be only partially supported, or deprecated entirely. If others are willing to step in and provide support for squeelize, mongoose, dynamo db, 42 gallon barrels, etc. it would be worth to make the architecture changes underneath.

If this is of interest to you, please comment. @M1chaelTran, @shemsargent-rvtd

**Comment by thelordoftheboards** [comment]
I created a milestone in order to track the different tasks related to the project:

https://github.com/codefoundries/UniversalRelayBoilerplate/milestone/6

**Comment by thelordoftheboards** [comment]
All the basic requirements to support multiple databases have been implemented. The support for any specific other database can be handled through separate issues. Ideally those implementations will not require any new changes outside of their respective units.
