### ISSUE TITLE
Fresh install Cassandra setup issues

### ISSUE THREAD

**Issue by dfcarpenter** [codefoundries/UniversalRelayBoilerplate#188]
Installed cassandra correctly but per docs running 

```
npm setup-cassandra-init 
```` 
doesn't work. Anyways, looked at package.json and realized it's now just setup-cassandra. Also in 
setup-cassandra.js the path is incorrect for ExpressCassandra.js. Anyways fixing those I get an 'urb' keyspace but no tables created. Not sure how to do so. 

Thanks

**Comment by thelordoftheboards** [comment]
Did you download the latest release, or master?

I am in the process of refactoring this whole thing, in order to add support for Monogo, Dynamo Db and MySQL. I will be refactoring this very shortly and uploading the updated documentation. As part of this, I will completely re-set my local setup and go through all the setup steps again and fix whatever is broken in the scripts and the documentation.

**Comment by thelordoftheboards** [comment]
I looked at the code, indeed while refactoring I messed up the script. Either use the previous point release, or wait for the next one, I should be able to cut it within the next couple of days.

**Comment by dfcarpenter** [comment]
Wow! Thanks for getting to this so quickly. Ill test this out this afternoon.
