### ISSUE TITLE
[app] cannot read property getScrollableNode of undefined

### ISSUE THREAD

**Issue by skarpyak** [codefoundries/UniversalRelayBoilerplate#342]
trying to install v.15.0.0 on mac, web works fine, but ios always have error: 
![image](https://user-images.githubusercontent.com/8594755/28996338-57688a8c-7a07-11e7-917e-3b81d868b596.png)

Cannot read property 'getScrollableNode' of undefined
Unhandled JS Exception: Cannot read property 'getScrollableNode' of undefined
Possible Unhandled Promise Rejection (id: 0):
RelayQL: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `Relay.QL`.
Invariant Violation: RelayQL: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `Relay.QL`.
![image](https://user-images.githubusercontent.com/8594755/29002797-4cc336ac-7ab3-11e7-8e5b-289dec6dfe87.png)

**Comment by skarpyak** [comment]
everything fine :) My issue was result  'react-native upgrade' this command can rewrite .babelrc and remove babel plugin settings

**Comment by thelordoftheboards** [comment]
Unfortunately I have not worked on transferring the native code to the new boilerplate - it should mostly work from the previous boilerplate, but the GraphQL names should be changed. Also, I will separate the app into distinct units instead of bundling everything by functionality like in the previous version.
