### ISSUE TITLE
Unclear Separation from Rebar

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [codefoundries/UniversalRelayBoilerplate#44]
The UniversalRelayBoilerplate website seems to use UniversalRelayBoilerplate, Rebar, and in some cases, IMRSK interchangeably.  For example, the [Rebar Development Setup](http://codefoundries.com/developer/rebar/development-setup.html) page explains how to set up UniversalRelayBoilerplate, but not Rebar.  This makes it difficult to determine whether or not the user is getting the advanced features of Rebar, and, if not, how to get Rebar or if Rebar is even available.  Would it be possible to have the separation between the two projects more clearly defined?

**Comment by thelordoftheboards** [comment]
I will update the documentation to be more clear.

IMRSK is pretty much the previous incarnation of UniversalRelayBoilerplate. I left it as is, since the project has the react native separated from the web/server part, and that setup might be convenient for some folks, especially considering the amount of changes happening in React Native. I do not intend to make any further improvements to it, but if someone else wants to I'd gladly accept PRs.

Rebar is pretty much an upgrade of UniversalRelayBoilerplate with some additional modules. I will insert 'applies to' comments to designate whether something is urb, rebar, or both. From efficiency standpoint it makes sense to have only one version of the documentation.

**Comment by wtgtybhertgeghgtwtg** [comment]
Thank you for the prompt response.  Is Rebar currently available or intended to be made available, or it is a purely in-company project?

**Comment by thelordoftheboards** [comment]
Rebar is currently used in couple of projects for clients but is not in a state where it can be made available.

**Comment by thelordoftheboards** [comment]
I updated the documentation using 'boilerplate' where the content applies to both Rebar and URB, and added notes 'Rebar only' where applicable. Hopefully that prevents any further confusion. Thank you for suggesting the change.
