### ISSUE TITLE
Node requests not working

### ISSUE THREAD

**Issue by navasiloy** [codefoundries/UniversalRelayBoilerplate#82]
The GraphQL requests like
{
 node(id:"VG9EbzozNDIwNDUwMC0yMzJlLTQzZGYtYmU5MC02NTE3MDJkMTE4MWQ=") {
   id
 }
}
are not working

http://universal-relay-boilerplate.herokuapp.com/graphql?query=%7B%0A%20%20node(id%3A%22YXJyYXljb25uZWN0aW9uOjA%3D%22)%20%7B%0A%20%20%20%20id%0A%20%20%7D%0A%7D

**Comment by thelordoftheboards** [comment]
```
Authentication failed
```

Unfortunately right now GraphiQL can only be accessed from one IP specified in USER_TOKEN_2_BYPASS_IP. By default it is set to 127.0.0.1 so that if you are working locally you would be able to access it. I also included a warning in https://github.com/codefoundries/UniversalRelayBoilerplate/blob/master/configuration/webapp/components/HomeScreen.jsx but have not updated Heroku with that yet.
I would love to hear a more elegant solution to the GraphiQL issue, but as it stands, the authentication failed error message is working as expected.

**Comment by thelordoftheboards** [comment]
I added the following explanation hope it helps:

![image](https://cloud.githubusercontent.com/assets/7056535/15455973/a9fc8de8-2017-11e6-9020-aa3595b8bae1.png)

If you have issues with a specific query when running it as described above please open another issues.

**Comment by navasiloy** [comment]
That was not authentication issue
Before to access graphql I've used https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en

where i added header: user_auth_token=J0Lta9rNHT9MmWeaNHUqLR13jnkdsubh32o9HbVGqeFyiTHJKd2OI3NVaBfigd9suhkjhVHJ802MVIJ9tyvhdhk31s902BT82974h4RfuGVtbh32o902BT8Jiew29uT913sHU

which was previously in env file
so I has access early today :)


The issue is: 
REQUEST
---------
{
node(id:"id") {
  id
 }
}

RESPONSE 
----------
{
  "data": {
    "node": null
  },
  "errors": [
    {
      "message": "Cannot read property 'loaders' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 1
        }
      ]
    }
  ]
}

**Comment by thelordoftheboards** [comment]
Thank you for the additional detail this needs to be looked at. I noticed there was another issue with the im-memory storage, possibly they are related.

**Comment by thelordoftheboards** [comment]
The code needs to change to:

```
  const { id, type } = fromGlobalId(args.id);
```

and then:

```
  if( type === 'Viewer' )
    return objectManager.getOneById( 'User', id );
  else
    return objectManager.getOneById( type, id );
```
